name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GOLANG_VERSION: 1.25

jobs:
  test:
    name: Test, Lint and Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '$GOLANG_VERSION'
          check-latest: true

      - name: Dependencies 
        run: |
          go mod verify
          go mod tidy
          git diff --exit-code # Ensures go.mod and go.sum are up to date

      - name: Run Tests 
        run: |
          go test -v -race -shuffle=on ./...

      - name: Run Examples 
        run: |
          go run example/list/main.go
          go run example/idlist/main.go

      - name: Run golangci-lint manually
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run --timeout=10m

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: $GOLANG_VERSION 
           go-package: ./...

